### ISSUE TITLE
Gmail - invalid credentials

### ISSUE THREAD

**Issue by mdouchin** [axllent/imap-scrub#3]
Hi,
Thanks a lot for this tool which seems to be exactly what I need !

I cannot connect to my Gmail account, I get: 
```Connecting to imap.gmail.com:993...
Invalid credentials (Failure)
```
Does connecting to Gmail still work with login/password ? Does Gmail enforce the use of OAuth ?

**Comment by mdouchin** [comment]
NB: I have a `!` in my password.

**Comment by axllent** [comment]
It should be able to connect, but not via OAuth. For a regular gmail account, I believe you now have to now set up "2-Step Verification", and then add an app password (this is how I do it on a Google Workspace account anyway).

**Comment by mdouchin** [comment]
Exactly ! The app password and 2steps auth worked like a charm. Thanks a lot !

**Comment by axllent** [comment]
Awesome :)

**Comment by mdouchin** [comment]
I let this closed, I just would like to THANK YOU. Your tool is awesome !

**Comment by axllent** [comment]
Thank you - I'm really glad you find it useful!
